### ISSUE TITLE
Use images from articles and not from thumbnails

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/berlinglish#14]
This PR https://github.com/viniciuskneves/berlin_en_news/pull/13 introduced images to Tweets.

So far we're using thumbnails which are low resolution and can get blurry once you open Twitter on a computer.

We could use the images from the articles instead, which have a higher resolution and sometimes even more than one image.

Article with one image: https://www.berlin.de/en/news/coronavirus/6122241-6098215-coronavirus-restrictions-longer-stay-in-.en.html
Article with 2 images: https://www.berlin.de/en/news/coronavirus/6123872-6098215-retail-calls-on-supermarket-customers-to.en.html

@leonardopavanrocha FYI

**Comment by leonardopavanrocha** [comment]
@viniciuskneves  It makes sense to use the article image instead of the thumbnail. Since I am already familiar with this issue, I can implement this during the week.
